FROM python:3.12-slim-bookworm

WORKDIR /delaysapi

COPY ./requirements.txt /delaysapi/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /delaysapi/requirements.txt

COPY ./app /delaysapi/app

COPY ./templates /delaysapi/templates

CMD ["uvicorn", "app.delays_api:app", "--host", "0.0.0.0", "--port", "8000"]